[[colors.indexed_colors]]
color = "0xcb4b16"
index = 16

[[colors.indexed_colors]]
color = "0xd33682"
index = 17

[[colors.indexed_colors]]
color = "0x073642"
index = 18

[[colors.indexed_colors]]
color = "0x586e75"
index = 19

[[colors.indexed_colors]]
color = "0x839496"
index = 20

[[colors.indexed_colors]]
color = "0xeee8d5"
index = 21

[colors.bright]
black = "0x657b83"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0x6c71c4"
red = "0xdc322f"
white = "0xfdf6e3"
yellow = "0xb58900"

[colors.cursor]
cursor = "0x93a1a1"
text = "0x002b36"

[colors.normal]
black = "0x002b36"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0x6c71c4"
red = "0xdc322f"
white = "0x93a1a1"
yellow = "0xb58900"

[colors.primary]
# background = "0x102235"
background = "0x102020"
foreground = "0x93a1a1"

[env]
TERM = "xterm-256color"

[font]
size = 20.0

# [font.bold]
# family = "SauceCodePro Nerd Font"
# style = "Bold"

# [font.bold_italic]
# family = "Hurmit Nerd Font"
# style = "Bold Italic"
#
# [font.italic]
# family = "Hurmit Nerd Font"
# style = "Bold Italic"

# [font.normal]
# family = "CaskaydiaMono NF"
# style = "Regular"

[font.normal]
family = "Mononoki Nerd Font Mono"
style = "Bold"

[font.offset]
x = 0
y = 0

[scrolling]
history = 5000

[window]
title = "Alacritty"
opacity = 0.85

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
